import { Inter } from "next/font/google";
import "@/styles/globals.css";
import ReportProvider from "@/components/providers/ReportProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark bg-secondary text-secondary-foreground">
      <body className={inter.className}>
        <ReportProvider>{children}</ReportProvider>
      </body>
    </html>
  );
}
